[package]
name = "ricp"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
num_cpus = "1.17.0"
rayon = "1.12.0"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "solver_benchmarks"
harness = false

[profile.release]
opt-level = 3
lto = true          # Enables Link-Time Optimization across crates
codegen-units = 1   # Reduces parallel code generation to allow better global optimization
