site_name: ricp
site_url: https://ezrantn.github.io/ricp
site_author: Ezra Natanael
site_description: A Ridiculously Fast, Sound & Lock-Free Non-linear Real Arithmetic (NRA) Theory Engine in Pure Rust.

repo_name: ezrantn/ricp
repo_url: https://github.com/ezrantn/ricp
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  # - Architecture: architecture.md
  # - Benchmarks: benchmarks.md
  # - CLI Usage: cli.md
  # - API Reference: api.md